# Generated by Django 3.1.7 on 2021-03-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
